# Generated by Django 4.0.6 on 2022-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
