# Generated by Django 4.0.6 on 2022-08-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoomNumber',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booking_roomnumber', serialize=False, to='Hotel.booking')),
                ('room_number', models.CharField(max_length=100)),
            ],
        ),
    ]
