# Generated by Django 4.0.6 on 2022-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_bookingroomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomgroup',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
