# Generated by Django 4.0.6 on 2022-08-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_hotel_image_roomgroup_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.paymentinformations'),
        ),
        migrations.AlterField(
            model_name='finishpayment',
            name='paid_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finishpayment',
            name='transactionid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
