# Generated by Django 4.0.6 on 2022-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_booking_payment_info_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_info',
        ),
    ]
